transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/ip/edge_detect {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/ip/edge_detect/altera_edge_detector.v}
vlog -vlog01compat -work work +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/ip/altsource_probe {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/ip/altsource_probe/hps_reset.v}
vlog -vlog01compat -work work +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/ghrd.v}
vlib soc_system
vmap soc_system soc_system
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/soc_system.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_sysid_qsys.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/rc4_avalon_interface.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/rc4.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_onchip_memory2_0.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_leds.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_jtag_uart.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/intr_capturer.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_hps_0.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_hps_0_hps_io.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_fpga_only_master.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_idle_inserter.v}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_irq_mapper_001.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_irq_mapper.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_avalon_st_pipeline_base.v}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_001.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_axi_slave_ni.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux_002.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux_004.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux_002.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux_004.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux_002.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux_002.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_009.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_007.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_006.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_005.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_003.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_002.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_hps_0_hps_io_border.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_hps_0_fpga_interfaces.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_fpga_only_master_p2b_adapter.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_fpga_only_master_b2p_adapter.sv}
vlog -sv -work soc_system +incdir+/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules {/home/sebastian/workspace/verilog/my_first_hps-fpga_base/soc_system/synthesis/submodules/soc_system_fpga_only_master_timing_adt.sv}

